version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=my_spring_boot_db
      - DB_USERNAME=root
      - DB_PASSWORD=password123
      - JPA_DDL_AUTO=update
      - JPA_SHOW_SQL=false
      - JPA_FORMAT_SQL=false
      - LOG_SQL=INFO
      - LOG_SQL_PARAMS=INFO
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - spring-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=my_spring_boot_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - spring-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password123
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge
